#!/bin/sh

PFW=$(pfw)
WW=$(wattr w $PFW)
WH=$(wattr h $PFW)
CUR=${2:-$(pfw)}
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)
BWIDTH=$(wattr b $CUR)
PANEL=27
GAP=9
BW=3
ACTIVE=0x$(getxresource color0 | cut -d# -f2)
INACTIVE=0x000000
