#!/bin/bash

[ -d ~/.vim/autoload ] || ( mkdir ~/.vim/autoload && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim )
[ -d ~/.vim/bundle ] || mkdir ~/.vim/bundle
rm -rf ~/.vim/bundle/*
cd ~/.vim/bundle
git clone https://github.com/tpope/vim-surround
git clone https://github.com/tpope/vim-commentary
git clone https://github.com/tpope/vim-repeat
git clone https://github.com/tpope/vim-dispatch
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/haya14busa/vim-operator-flashy
git clone https://github.com/haya14busa/incsearch.vim
git clone https://github.com/haya14busa/vim-asterisk
git clone https://github.com/Shougo/unite.vim
git clone https://github.com/easymotion/vim-easymotion
git clone https://github.com/Raimondi/delimitMate
git clone https://github.com/kana/vim-operator-user
git clone https://github.com/AndrewRadev/switch.vim
git clone https://github.com/SirVer/ultisnips
git clone https://github.com/udalov/kotlin-vim
git clone https://github.com/akhaku/vim-java-unused-imports
git clone https://github.com/jvenant/vim-java-imports
git clone https://github.com/kazufukurou/skk.vim
git clone https://github.com/kazufukurou/vim-android-sensible
