#! /bin/sh

. ~/.config/bspwm/panel_config
. ~/.config/bspwm/panel_colors
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.5
bspc config auto_cancel true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config active_border_color $PANEL_COLOR_GRAY
bspc config focused_border_color $PANEL_COLOR_MAGENTA
bspc config normal_border_color $PANEL_COLOR_GRAY
bspc config presel_border_color $PANEL_COLOR_WHITE
bspc config top_padding $PANEL_HEIGHT

bspc monitor -d 1 2 3 4 5 6 7 8 9
~/bin/bgcolor &
~/.config/bspwm/panel &
