#! /bin/sh

color_gray=$(~/bin/getxresource color0)
color_lightgray=$(~/bin/getxresource color8)
bspc config split_ratio 0.5
bspc config auto_cancel true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config active_border_color $color_gray
bspc config focused_border_color $color_lightgray
bspc config normal_border_color $color_gray
bspc config presel_feedback_color $color_lightgray
bspc config external_rules_command $(which ~/.config/bspwm/external_rules)

bspc config border_width 3
bspc config -m next border_width 3
bspc config window_gap 6
bspc config top_padding 24

bspc monitor -d 0 1 2 3 4 5 6 7 8
bspc monitor next -d 9
bspc rule -a URxvt -o manage=off
bspc rule -a feh state=pseudo_tiled
xsetroot -cursor_name left_ptr
xsetroot -solid $color_gray
urxvt -geometry 212x1 -bw 0 -b 0 -bg $color_gray -e ~/.config/bspwm/panel &
