#! /bin/sh

fwid=$(bspc query -N -n focused.automatic)

if [ -n "$fwid" ] ; then
    width=$(xwininfo -id $fwid | grep Width | cut -d: -f2)
    height=$(xwininfo -id $fwid | grep Height | cut -d: -f2)
    if [ $width -gt $height ] ; then
        echo "split_dir=east"
    else
        echo "split_dir=south"
    fi
    echo "split_ratio=0.5"
fi
