#! /bin/sh

. ~/.config/bspwm/panel_config

WORKSPACES=('▘' '▀' '▝' '▌' '█' '▐' '▖' '▄' '▗' '')

while read -r line ; do
    case $line in
        S*)
            sys_infos="${line#?}"
            ;;
        T*)
            title="${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    O*|F*|U*)
                        wm_infos="${wm_infos}${WORKSPACES[${name} - 1]}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "%{l} %{F$PANEL_COLOR_WHITE}${wm_infos}%{F-} ${title}%{r}${sys_infos} "
done
