#! /bin/sh

PANEL_HEIGHT=24
PANEL_FONT_FAMILY="M+ 1p:size=12:antialias=true"
PANEL_COLOR_BG=$(~/bin/getxresource background)
PANEL_COLOR_BLUE=$(~/bin/getxresource color4)
PANEL_COLOR_MAGENTA=$(~/bin/getxresource color5)
PANEL_COLOR_RED=$(~/bin/getxresource color1)
PANEL_COLOR_RED_BOLD=$(~/bin/getxresource color9)
PANEL_COLOR_WHITE=$(~/bin/getxresource color7)
PANEL_COLOR_GRAY=$(~/bin/getxresource color0)
